name: Zstats
version: 0.4
main: zerrium.Zstats
api-version: 1.13
author: zerrium
softdepend: [DiscordSRV, Essentials]
commands:
  zstats:
    description: Modify player stats data on database
    usage: /zstats <update/delete> <player_name>
    permission: Zstats.use